from tkinter import *
root=Tk()
root.geometry("700x700")
# root.resizable(0,0)
f1=Frame(root,bg="grey",borderwidth=6,relief=SUNKEN)
f1.pack(side=LEFT,fill=Y)
f2=Frame(root,bg="grey",borderwidth=6,relief=SUNKEN)
f2.pack(side=RIGHT,fill=Y)
l1=Label(f1,text="My project")
l1.pack(pady=150)
l2=Label(f2,text="My project")
l2.pack(pady=150)
f3=Frame(root,bg="grey",borderwidth=6,relief=SUNKEN)
f3.pack(side=TOP)
l3=Label(f3,text="X axies")
l3.pack(padx=100)
f4=Frame(root,bg="grey",borderwidth=6,relief=SUNKEN)
f4.pack(side=BOTTOM)
l4=Label(f4,text="X axies")
l4.pack(padx=100)

root.mainloop()